version: "3.5"
services:
  todo_db:
    container_name: todo_db
    image: postgres:14.5
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    ports:
      - 5432:5432
  todo:
    container_name: todo
    build:
      context: .
      dockerfile: Dockerfile
      args:
        TODO_DB_HOSTNAME: todo_db
    environment:
      HISTFILE: /root/hist/.zsh_history
    volumes:
      # This is where VS Code should expect to find your project's source code
      # and the value of "workspaceFolder" in .devcontainer/devcontainer.json
      - ..:/workspace:cached
      # keep my bash history even if we delete the image
      - bashhistory:/root/hist
    command: /bin/zsh -c "while sleep 1000; do :; done"

volumes:
  bashhistory:
